spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/leaderboard
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:h2:tcp://localhost/~/leaderboard-test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
